name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Build web assets
      run: |
        npm run build
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Configure Keystore
      run: |
        # Cria diretório para o keystore
        mkdir -p ~/.android
        # Copia o keystore para o local correto
        cp release.keystore ~/.android/debug.keystore
        # Configura o arquivo de propriedades do keystore
        echo "storeFile=~/.android/debug.keystore" > android/keystore.properties
        echo "storePassword=app-mercado" >> android/keystore.properties
        echo "keyAlias=app-mercado" >> android/keystore.properties
        echo "keyPassword=app-mercado" >> android/keystore.properties
        
    - name: Build Android APK
      run: |
        npx cap sync android
        cd android
        # Cria diretório de saída
        mkdir -p app/build/outputs/apk/release
        # Gera o APK assinado
        ./gradlew assembleRelease
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
